# Generated by Django 6.0 on 2026-01-20 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orcid', models.CharField(blank=True, help_text='ORCID identifier for the contributor', validators=[django.core.validators.RegexValidator(message='This field must be a valid ORCID', regex='^https://orcid.org/\\\\d{4}-\\\\d{4}-\\\\d{4}-\\\\d{4}$')])),
                ('external_identifiers', models.JSONField(blank=True, default=dict, help_text='External identifiers')),
                ('name', models.CharField(help_text='Full name of the contributor')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('institution', models.CharField(blank=True, help_text='Institutional affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_year', models.IntegerField(blank=True, help_text='Start year of the funding award', validators=[django.core.validators.RegexValidator(message='This field must be a valid year', regex='\\d{4}')])),
                ('end_year', models.IntegerField(blank=True, help_text='End year of the funding award', validators=[django.core.validators.RegexValidator(message='This field must be a valid year', regex='\\d{4}')])),
                ('funding_institute', models.CharField(help_text='Name of the funding institute (e.g., NIH, NSF, DARPA)')),
                ('award_number', models.CharField(help_text='Funding award or grant number')),
                ('award_title', models.CharField(blank=True, help_text='Title of the funded award')),
                ('funding_url', models.URLField(blank=True, help_text='URL to the funding announcement or award page')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publication_doi', models.CharField(blank=True, help_text='DOI for the publication', validators=[django.core.validators.RegexValidator(message='This field must be formatted as DOI', regex='^10\\\\.\\\\d{4,9}/[-._;()/:A-Z0-9]+$')])),
                ('title', models.CharField(help_text='Title of the publication')),
                ('journal', models.CharField(blank=True, help_text='Journal or venue where the work was published')),
                ('year', models.IntegerField(blank=True, help_text='Year of publication', validators=[django.core.validators.RegexValidator(message='This field must be a valid year', regex='\\d{4}')])),
                ('publication_url', models.URLField(blank=True, help_text='URL to the publication landing page or preprint')),
            ],
        ),
        migrations.CreateModel(
            name='EmberProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(help_text='Project identifier')),
                ('project_title', models.CharField(help_text='Title of the project')),
                ('project_description', models.TextField(help_text='Text description of the project')),
                ('model_organism', models.JSONField(blank=True, default=list, help_text='Model organisms used in this project (e.g., Mus musculus, Homo sapiens)')),
                ('data_use_agreement', models.TextField(blank=True, help_text='Description or reference to the data use agreement governing access to restricted or controlled data')),
                ('data_use_agreement_required', models.BooleanField(default=False, help_text='Indicates whether a data use agreement is required to access any project data')),
                ('data_availability_emberdandi', models.BooleanField(default=False, help_text='Indicates if data is available in EMBER-DANDI', verbose_name='Data in EMBER-DANDI?')),
                ('data_availability_emberrestricted', models.BooleanField(default=False, help_text='Indicates if data is available in EMBERrestricted', verbose_name='Data in EMBERrestrictred?')),
                ('data_availability_embervault', models.BooleanField(default=False, help_text='Indicates if data is available in EMBERvault', verbose_name='Data in EMBERvault?')),
                ('access_tier_summary', models.TextField(blank=True, help_text='Text description of different data tiers')),
                ('last_metadata_update', models.DateTimeField(help_text='Date and time of last metadata update')),
                ('metadata_version', models.CharField(default='1', help_text='Version of the metadata')),
                ('ember_doi', models.CharField(blank=True, help_text='DOI in EMBER system (empty string allowed until assigned)', validators=[django.core.validators.RegexValidator(message='This field must be formatted as DOI', regex='^10\\\\.\\\\d{4,9}/[-._;()/:A-Z0-9]+$')])),
                ('access_level_emberdandisets', models.JSONField(blank=True, default=list, help_text='EMBER-DANDI dandiset ids', validators=[django.core.validators.RegexValidator(message='This field must be a valid EMBER-DANDI id', regex='EMBER-DANDI:\\\\d{6}$')])),
                ('access_level_restricted_datasets', models.JSONField(blank=True, default=list, help_text='Restricted dataset ids')),
                ('access_level_access_vault_ids', models.JSONField(blank=True, default=list, help_text='EMBERvault dataset ids')),
                ('related_repositories', models.JSONField(blank=True, default=list, help_text='Identifiers for related repositories')),
                ('related_dandisets', models.JSONField(blank=True, default=list, help_text='DOIs for related dandisets')),
                ('related_data', models.JSONField(blank=True, default=list, help_text='Identifiers for other related datasets')),
                ('data_administrator', models.ForeignKey(help_text='Primary point of contact for data management', on_delete=django.db.models.deletion.RESTRICT, to='projects.contributor')),
                ('funding', models.ManyToManyField(blank=True, help_text='Funding sources supporting this project', related_name='projects', to='projects.funding')),
                ('related_publications', models.ManyToManyField(blank=True, help_text='Publications associated with this project', to='projects.publication')),
            ],
            options={
                'verbose_name': 'EMBER Project',
                'verbose_name_plural': 'EMBER Projects',
            },
        ),
        migrations.CreateModel(
            name='PublicationContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contributor')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='Authors of the publication', through='projects.PublicationContributor', to='projects.contributor'),
        ),
    ]
