# Generated by Django 6.0 on 2026-01-07 16:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('contributor_id', models.CharField(help_text='Internal identifier for the contributor within EMBER metadata', primary_key=True, serialize=False)),
                ('external_identifiers', models.JSONField(blank=True, help_text='External identifiers such as ORCID')),
                ('name', models.CharField(help_text='Full name of the contributor')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('institution', models.CharField(blank=True, help_text='Institutional affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_institute', models.CharField(help_text='Name of the funding institute (e.g., NIH, NSF, DARPA)')),
                ('award_number', models.CharField(help_text='Funding award or grant number')),
                ('award_title', models.CharField(blank=True, help_text='Title of the funded award')),
                ('funding_url', models.URLField(blank=True, help_text='URL to the funding announcement or award page')),
            ],
        ),
        migrations.CreateModel(
            name='EmberProject',
            fields=[
                ('project_id', models.CharField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(help_text='Title of the project')),
                ('project_description', models.TextField(help_text='Text description of the project')),
                ('data_use_agreement', models.TextField(blank=True, help_text='Description or reference to the data use agreement governing access to restricted or controlled data')),
                ('data_use_agreement_required', models.BooleanField(default=False, help_text='Indicates whether a data use agreement is required to access any project data')),
                ('data_availability_emberdandi', models.BooleanField(default=False, help_text='Indicates if data is available in EMBER-DANDI', verbose_name='Data in EMBER-DANDI?')),
                ('data_availability_emberrestricted', models.BooleanField(default=False, help_text='Indicates if data is available in EMBERrestricted', verbose_name='Data in EMBERrestrictred?')),
                ('data_availability_embervault', models.BooleanField(default=False, help_text='Indicates if data is available in EMBERvault', verbose_name='Data in EMBERvault?')),
                ('access_tier_summary', models.TextField(blank=True, help_text='Text description of different data tiers')),
                ('last_metadata_update', models.DateTimeField(help_text='Date and time of last metadata update')),
                ('metadata_version', models.CharField(default='1', help_text='Version of the metadata')),
                ('ember_doi', models.CharField(blank=True, help_text='DOI in EMBER system (empty string allowed until assigned)', validators=[django.core.validators.RegexValidator(message='This field must be formatted as DOI', regex='^10\\\\.\\\\d{4,9}/[-._;()/:A-Z0-9]+$')])),
                ('access_level_emberdandisets', models.JSONField(blank=True, default=list, help_text='EMBER-DANDI dandiset ids', validators=[django.core.validators.RegexValidator(regex='EMBER-DANDI:\\\\d{6}$')])),
                ('access_level_restricted_datasets', models.JSONField(blank=True, default=list, help_text='Restricted dataset ids')),
                ('access_level_access_vault_ids', models.JSONField(blank=True, default=list, help_text='EMBERvault dataset ids')),
                ('related_publications', models.JSONField(blank=True, default=list, help_text='DOIs for related publications')),
                ('related_repositories', models.JSONField(blank=True, default=list, help_text='Identifiers for related repositories')),
                ('related_dandisets', models.JSONField(blank=True, default=list, help_text='DOIs for related dandisets')),
                ('related_data', models.JSONField(blank=True, default=list, help_text='Identifiers for other related datasets')),
                ('funding', models.ManyToManyField(blank=True, help_text='Funding sources supporting this project', related_name='projects', to='projects.funding')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.emberproject')),
            ],
        ),
        migrations.AddField(
            model_name='emberproject',
            name='data_administrator',
            field=models.ManyToManyField(blank=True, help_text='Primary point of contact for data management', related_name='projects', through='projects.ProjectContributor', to='projects.contributor'),
        ),
    ]
