/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description EMBER API Root */
    get: operations['api_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get all EMBER Projects */
    get: operations['projects_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get an EMBER Project by its project id */
    get: operations['projects_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Contributor: {
      readonly id: number;
      /** @description ORCID identifier for the contributor */
      orcid?: string;
      /** @description External identifiers */
      external_identifiers?: unknown;
      /** @description Full name of the contributor */
      name: string;
      /**
       * Format: email
       * @description Contact email address
       */
      email?: string;
      /** @description Institutional affiliation */
      institution?: string;
    };
    Funding: {
      readonly id: number;
      /** @description Start year of the funding award */
      start_year?: number;
      /** @description End year of the funding award */
      end_year?: number | null;
      /** @description Name of the funding institute (e.g., NIH, NSF, DARPA) */
      funding_institute: string;
      /** @description Funding award or grant number */
      award_number: string;
      /** @description Title of the funded award */
      award_title?: string;
      /**
       * Format: uri
       * @description URL to the funding announcement or award page
       */
      funding_url?: string;
    };
    Message: {
      message: string;
    };
    Project: {
      readonly id: number;
      readonly data_administrator: components['schemas']['Contributor'];
      readonly related_publications: components['schemas']['Publication'][];
      readonly funding: components['schemas']['Funding'][];
      readonly model_organisms: components['schemas']['Taxonomy'][];
      /** @description Project identifier */
      project_id: string;
      /** @description Title of the project */
      project_title: string;
      /** @description Text description of the project */
      project_description: string;
      /** @description Start year of the  project */
      year?: number;
      /** @description Keywords associated with the project */
      keywords?: unknown;
      /** @description Description or reference to the data use agreement governing access to restricted or controlled data */
      data_use_agreement?: string;
      /** @description Indicates whether a data use agreement is required to access any project data */
      data_use_agreement_required?: boolean;
      /**
       * Data in EMBER-DANDI?
       * @description Indicates if data is available in EMBER-DANDI
       */
      data_availability_emberdandi?: boolean;
      /**
       * Data in EMBERrestrictred?
       * @description Indicates if data is available in EMBERrestricted
       */
      data_availability_emberrestricted?: boolean;
      /**
       * Data in EMBERvault?
       * @description Indicates if data is available in EMBERvault
       */
      data_availability_embervault?: boolean;
      /** @description Text description of different data tiers */
      access_tier_summary?: string;
      /**
       * Format: date-time
       * @description Date and time of last metadata update
       */
      last_metadata_update: string;
      /** @description Version of the metadata */
      metadata_version?: string;
      /** @description DOI in EMBER system (empty string allowed until assigned) */
      ember_doi?: string;
      /** @description EMBER-DANDI dandiset ids */
      access_level_emberdandisets?: unknown;
      /** @description Restricted dataset ids */
      access_level_restricted_datasets?: unknown;
      /** @description EMBERvault dataset ids */
      access_level_access_vault_ids?: unknown;
      /** @description Identifiers for related repositories */
      related_repositories?: unknown;
      /** @description DOIs for related dandisets */
      related_dandisets?: unknown;
      /** @description Identifiers for other related datasets */
      related_data?: unknown;
      /** @description Custom content for the website project page */
      website_content?: string;
    };
    Publication: {
      readonly id: number;
      readonly authors: components['schemas']['Contributor'][];
      /** @description DOI for the publication */
      publication_doi?: string;
      /** @description Title of the publication */
      title: string;
      /** @description Journal or venue where the work was published */
      journal?: string;
      /** @description Year of publication */
      year?: number;
      /**
       * Format: uri
       * @description URL to the publication landing page or preprint
       */
      publication_url?: string;
    };
    /**
     * @description * `SPECIES` - Species
     *     * `GENUS` - Genus
     *     * `FAMILY` - Family
     * @enum {string}
     */
    RankEnum: 'SPECIES' | 'GENUS' | 'FAMILY';
    Taxonomy: {
      readonly id: number;
      /** @description NCBI Taxonomy ID */
      taxonomy_id: number;
      /**
       * @description Taxonomic rank
       *
       *     * `SPECIES` - Species
       *     * `GENUS` - Genus
       *     * `FAMILY` - Family
       */
      rank?: components['schemas']['RankEnum'];
      /** @description Current scientific name */
      current_scientific_name: string;
      /** @description Common name */
      common_name?: string;
      /** @description Image source path */
      image_source?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  api_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Message'];
        };
      };
    };
  };
  projects_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'][];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Message'];
        };
      };
    };
  };
  projects_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project Id */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Message'];
        };
      };
    };
  };
}
