name: Frontend CI

on: [pull_request]

jobs:
  format-check:
    name: Run Prettier formatting check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
      
      - name: Run dependencies
        run: yarn run format-check